spring.application.name=local-problem-solver
spring.datasource.url=jdbc:mysql://localhost:3306/local_problem_solver
spring.datasource.username=root
spring.datasource.password=warad123

spring.jpa.hibernate.ddl-auto=update